- name: Atualizar a lista de pacotes
  become: true
  apt:
    update_cache: yes

- name: Instalar pacotes necessários para adicionar repositórios APT
  become: true
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present

- name: Adicionar chave GPG oficial do Docker
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Adicionar repositório Docker
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present
    filename: docker

- name: Atualizar a lista de pacotes novamente
  become: true
  apt:
    update_cache: yes

- name: Instalar Docker Docker compose plugin e containerd
  become: true
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Garantir que o serviço Docker está ativo e habilitado
  become: true
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Adicionar usuário atual ao grupo docker
  become: true
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Criar diretório de configuração do containerd
  become: true
  file:
    path: /etc/containerd
    state: directory

- name: Remover arquivo de configuração padrão do containerd
  become: true
  file:
    path: /etc/containerd/config.toml
    state: absent

- name: Restartar containerd
  become: true
  systemd:
    name: containerd
    state: restarted
    enabled: yes
